# Connexion \u00E0 MySQL (Base de donn\u00E9es OCP)
spring.datasource.url=jdbc:mysql://localhost:3306/db_ocp_production
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuration de Swagger (pour tester tes APIs facilement)
springdoc.api-docs.path=/api-docs